[phases.setup]
nixPkgs = ["binutils", "gcc", "rust-bin.stable.latest.default"]

[phases.install]
cmds = ["cargo fetch"]

[phases.build]
env = { SQLX_OFFLINE = "true" }
cmds = ["mkdir -p bin","cargo build --release", "cp target/release/superchain-indexer bin"]

[variables]
SQLX_OFFLINE = "true"
RUST_LOG = "trace"
